name: Action Test

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set name
        run: git config user.name github-actions[bot]

      - name: Set email
        run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Run get_model_data script
        run: node ./script.js

      - name: stage changed files
        run: git add text.txt

      - name: commit changed files
        run: git commit -m "Auto updating text.txt"
      
      - name: fetch from master
        run: git fetch origin master

      - name: push code to master
        run: git push origin HEAD:master