name: Action Test

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Set name
        run: git config user.name github-actions[bot]

      - name: Set email
        run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run get_model_data script
        run: node ./script.js

      - name: check for changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            data:
              - 'docs/_data/**'

      - name: stage changed files
        if: steps.changes.outputs.data == 'true'
        run: git add docs/*

      - name: commit changed files
        if: steps.changes.outputs.data == 'true'
        run: git commit -m "Auto updating docs/"
      
      - name: fetch from master
        if: steps.changes.outputs.data == 'true'
        run: git fetch origin master

      - name: push code to master
        if: steps.changes.outputs.data == 'true'
        run: git push origin HEAD:master