name: Action Test

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          
      - run: ls

      - uses: actions/checkout@v3
        with:
          repository: neuronets/trained-models-template
          fetch-depth: 0
          path: .
          ref: main

      - run: ls

      - name: Run get_model_data script
        run: node ./script.js

      - name: Restructure file structure
        run: |
          mv ./trained-models-template/docs .
          rm -r ./trained-models-template

      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: Push to gh-pages
        run: git push origin gh-pages