name: Get Model Data

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Run get_model_data script
        run: node ./.github/workflows/get_model_data.js

      - name: stage changed files
        run: git add text.txt

      - name: commit changed files
        run: git commit -m "Auto updating text.txt"
      
      - name: fetch from master
        run: git fetch origin master

      - name: push code to master
        run: git push origin HEAD:master